server:
  port: 8140
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wdx9413/SpringcloudConfig
          username:
          password:
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka