spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#    globalcors:
#      corsConfigurations:
#        '[/**]':
#          allowedOrigins: "https://docs.spring.io"
#          allowedMethods:
#            - GET
server:
  port: 8120
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka